name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: prepare publish
        run: |
          echo npmAuthToken: "\${NPM_TOKEN}" >> ./.yarnrc.yml
      - name: pulish
        run: |
          yarn install --immutable | grep -v 'YN0013'
          yarn build
          yarn publish

