name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: build
        run: |
          yarn install --immutable | grep -v 'YN0013'
          yarn build

      - name: publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo npmAuthToken: "\${NPM_AUTH_TOKEN}" >> ./.yarnrc.yml
          yarn publish

      - name: cleanup
        run: |
          git checkout ./.yarnrc.yml

